---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: gateway-otelcol
  namespace: shortener
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib
  imagePullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      memory: 1024Mi
      cpu: 2000m
    limits:
      memory: 1024Mi
      cpu: 2000m
  config:
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      zpages:
        # view /debug/tracez
        endpoint: 0.0.0.0:55679

    connectors:
      spanmetrics:
        histogram: 
          unit: ms
          exponential:
            max_size: 160
        exemplars:
          enabled: true
        events:
          enabled: true
          dimensions:
          - name: event.name
          - name: exception.type
        aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"

    processors:
      batch: {}
      memory_limiter:
        limit_mib: 1024
        spike_limit_mib: 410
        check_interval: 5

    receivers:
      otlp:
        protocols:
          grpc: 
            endpoint: 0.0.0.0:4317
          http: 
            endpoint: 0.0.0.0:4318

    exporters:
      otlp/tempo:
        endpoint: tempo.tempo.svc.cluster.local:4317
        tls:
          insecure: true
      otlp_http/loki:
        endpoint: http://loki.loki.svc.cluster.local:3100/otlp
        tls:
          insecure: true

      prometheus_remote_write:
        endpoint: http://prom-stack-kube-prometheus-prometheus.prometheus:9090/api/v1/write
        tls:
          insecure: true

      debug:
        # basic, normal, detailed
        verbosity: detailed
        sampling_initial: 1
        sampling_thereafter: 100

    service:
      extensions: [ health_check, zpages ]
      pipelines:
        metrics:
          receivers: [ otlp, spanmetrics ]
          processors: [ batch, memory_limiter ]
          exporters: [ prometheus_remote_write, debug ]
        traces:
          receivers: [ otlp ]
          processors: [ batch, memory_limiter ]
          exporters: [ otlp/tempo, spanmetrics, debug ]
        logs:
          receivers: [ otlp ]
          processors: [ batch, memory_limiter ]
          exporters: [ otlp_http/loki, debug ]

---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: shortener-otelinst
  namespace: shortener
spec:
  exporter:
    endpoint: http://gateway-otelcol-collector.shortener.svc.cluster.local:4317
  propagators:
  - tracecontext
  - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  env:
  - name: OTEL_EXPORTER_OTLP_PROTOCOL
    value: grpc

  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: otlp
    - name: OTEL_METRICS_EXPORTER
      value: otlp

  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
    env:
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: otlp
    - name: OTEL_METRICS_EXPORTER
      value: prometheus
    - name: OTEL_EXPORTER_PROMETHEUS_HOST
      value: 0.0.0.0
    - name: OTEL_EXPORTER_PROMETHEUS_PORT
      value: "9464"
