spring.application.name=jredirector

server.port=${PORT:3001}
server.forward-headers-strategy=native

spring.data.redis.url=${REDIS_URL:redis://localhost:6379/0}

spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/shortener}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
